# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:16

stages:
    - sec
    - tests
    - deploy

#sast:
#    stage: sec
#include:
#    - template: Security/SAST.gitlab-ci.yml

utests:
    stage: tests
    script:
        - cd ritzkick && npm install
        - npm run test-ci
    services:
        - mongo:3.2

test-deploy:
    stage: deploy
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY_GCLOUD")
        - ssh-add <(echo "$SSH_PRIVATE_KEY_GCLOUD_GIT")
        - mkdir -p ~/.ssh/
        - echo -e "Host $GCLOUD_IP \n\tForwardAgent yes" > ~/.ssh/config
        - more ~/.ssh/config
        - ssh -o StrictHostKeyChecking=no $GCLOUD_USER@$GCLOUD_IP "cd ~/p-synthese-csfoy-ritzkick/ &&
          git fetch origin main && git reset --hard origin/main && cd ritzkick && sudo ./run.sh && exit"
    only:
        refs:
            - main
