image: node:16

stages:
    - sec
    - tests
    - deploy

#================
# SECURITY
#================

# Performance
#sast:
#    stage: sec
#include:
#    - template: Security/SAST.gitlab-ci.yml

#================
# TESTING
#================

# utests:
#     stage: tests
#     script:
#         - cd ritzkick && npm install
#         - npm run test-ci
#     services:
#         - mongo:latest
#     only:
#         refs:
#             - main
#         changes:
#             - ritzkick/**/*

#================
# DEPLOYMENT
#================

deploy:
    stage: deploy
    script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY_GCLOUD")
        - ssh-add <(echo "$SSH_PRIVATE_KEY_GCLOUD_GIT")
        - mkdir -p ~/.ssh/
        - echo -e "Host $GCLOUD_IP \n\tForwardAgent yes" > ~/.ssh/config
        - more ~/.ssh/config
        - ssh -o StrictHostKeyChecking=no $GCLOUD_USER@$GCLOUD_IP "cd /home/p-synthese-csfoy-ritzkick/ &&
          git fetch origin main && git reset --hard origin/main && cd ritzkick && sudo ./run.sh && exit"
    only:
        refs:
            - main
        changes:
            - ritzkick/**/*
